site_name: Repseq Library for Immune repertoire postanalysis
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - MiXCR module: mixcr.md
  - Postanalysis: postanalysis.md
  - Clone filter: filter.md
  - Supporting modules: supporting_modules.md
  - Test page: page2.md
  - Examples: examples.md
  # - Code Reference: reference/



extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mmjmike


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  # - search
  # - gen-files:
  #     scripts:
  #       - docs/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # - section-index
  - mkdocstrings:
      handlers:
          python:
            paths: [./repseq]
            #     setup_commands:
            #         - import sys
            #         - sys.path.append('../')
            #     selection:
            #         new_path_syntax: true
      

copyright: |
  &copy; 2023 <a href="https://github.com/mmjmike" target="_blank" rel="noopener">Mikhail Myshkin</a>